version: "3.7"
services:
  sleeper:
    image: local/${DOCKER_IMAGE_NAME}:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production
  sleeper-gpu:
    image: local/${DOCKER_IMAGE_NAME}-gpu:${DOCKER_BUILD_TARGET}
    build:
      context: ./
      dockerfile: docker/custom/Dockerfile
      target: production